### ISSUE TITLE
Question about the -proteinExport function

### ISSUE THREAD

**Issue by cksakura** [mpc-bioinformatics/pia#108]
Hello,
I tried the -proteinExport function for processing the sample data and found problems in the result. I used the command line `-infile yeast-gold-015-filtered.pia.xml -paramFile parameter.xml -proteinExport yeast-gold-015-filtered.csv csv`, the parameter file is the sample provided at [https://github.com/mpc-bioinformatics/pia/wiki/parameters-XML-file](url) and I changed the score names.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <tool docurl="http://www.medizinisches-proteom-center.de" name="pipeline" version="0.1.23">
    <description>This file will contains a pipeline execution for PIA</description>
    <PARAMETERS>
        <NODE description="Sets whether PSM sets should be built to combine search results from different search engines / runs." name="PSMCreatePSMSets">
            <ITEM value="yes" type="string" name="create sets"/>
        </NODE>
        <NODE description="Adds the given score name to the list of preferred scores for FDR calculation." name="PSMAddPreferredFDRScore">
            <ITEM value="PSM q-value" type="string" name="score name"/>
        </NODE>
        <NODE description="Adds the given score name to the list of preferred scores for FDR calculation." name="PSMAddPreferredFDRScore">
            <ITEM value="X!Tandem Expect" type="string" name="score name"/>
        </NODE>
        <NODE description="Sets the number of top identifications per spectrum used for all further FDR calculations, 0 meaning all identifications are used." name="PSMSetAllTopidentificationsForFDR">
            <ITEM value="1" type="string" name="number of top identifications"/>
        </NODE>
		<NODE description="Sets the regular expression used for decoy detection or if 'searchengine' is given as pattern, assumes a decoy search directly performed by the search engine." name="PSMSetAllDecoyPattern">
            <ITEM value="s.*" type="string" name="decoy pattern"/>
        </NODE>
        <NODE description="Calculates the FDR scores for all files." name="PSMCalculateAllFDR"/>
        <NODE description="Calculates the combined FDR score. The FDR scores for the single files should be calculated before." name="PSMCalculateCombinedFDRScore"/>
        <NODE description="Sets whether modifications should be considered while inferring the peptides from the PSMs. Defaults to false" name="PeptideConsiderModifications">
            <ITEM value="no" type="string" name="consider modifications"/>
        </NODE>
        <NODE description="Adds a filter used by the protein inference. A filter is added by its name, an abbreviation for the comparison, the compared value and (optional), whether the comparison should be negatede.g. &quot;AddInferenceFilter=charge_filter,EQ,2,no&quot;" name="ProteinAddInferenceFilter">
            <ITEM value="psm_score_filter_psm_combined_fdr_score" type="string" name="filtername"/>
            <ITEM value="LEQ" type="string" name="comparison"/>
            <ITEM value="0.01" type="string" name="value"/>
            <ITEM value="no" type="string" name="negate"/>
        </NODE>
        <NODE description="Inferes the proteins with the given inference method. Any inference filters should be set before this call with calls of AddInferenceFilter. The scoring method is set with the second argument. The scoring settings can be given by athird argument containing setting=value[;setting=value]* (usual settings are used_score and used_spectra)." name="ProteinInfereProteins">
            <ITEM value="inference_spectrum_extractor" type="string" name="inference"/>
            <ITEM value="scoring_multiplicative" type="string" name="scoring"/>
            <ITEM value="combined_fdr_score" type="string" name="used score"/>
            <ITEM value="best" type="string" name="used spectra"/>
        </NODE>
    </PARAMETERS>
</tool>`

In the generated result file, the score column is "NaN". 
`accessions | score | #peptides | #PSMs | #spectra
<p>P36071 | NaN | 1 | 1 | 1
<p>P25294 | NaN | 3 | 12 | 12
<p>P48415 | NaN | 1 | 1 | 1
<p>P38249 | NaN | 6 | 12 | 12`

But there were score values in the sample result file yeast-gold-015-filtered-proteins.csv, and three columns "isDecoy" "FDR" "q-value" were missed in my result. I'm not sure in which step I failed in the process.

Thank you for your help.

Kai Cheng

**Comment by julianu** [comment]
Hello Kai Cheng, I will have a look into the problem when I am back from the christmas holidays. Please stand by...

**Comment by cksakura** [comment]
Hello Uszkoreit,

Thank you very much, please take your time.
Happy holidays!

Best regards,
Kai

**Comment by julianu** [comment]
Hej Kai,

Sorry for the long delay, but here are the answers to your problem:
1) In the PSMAddPreferredFDRScore tags, the "short versions" of the score names must be used. At https://github.com/mpc-bioinformatics/pia/wiki/Score-Names is a (not complete) list of these. So, if you wanted to use the pre-calculated FDR q-values, psm_q_value would be correct, and xtandem_expect for the X!Tandem expect values. Nevertheless, I would for this file rather suggest to use xtandem_expect and msgf_specevalue (MSGF:Spectrum e-value) for the calculation of the FDR scores.
2) In the ProteinInfereProteins tag, psm_combined_fdr_score must be used instead of combined_fdr_score. This was wrong (from older versions) in the Wiki page, but is corrected now. Sorry for this, but especially the command line documentation is not as updated as it should be.

I attached the modified workflow XML file. Please let me know, whether this works for you.

Best,
Julian

[pia_workflow-changed.zip](https://github.com/mpc-bioinformatics/pia/files/1636449/pia_workflow-changed.zip)

**Comment by cksakura** [comment]
Hello Julian,

I'm very appreciate for your help, it works well now.
May I ask a question?
From the web server of PIA, I find in the ProteinInfereProteins tag, there
are two options for "used spectra", "best" and "all" (I'm not sure if more
options exist). Which one dose you recommend?
Generally, is there a set of "recommended parameters" for this task?

Thank you again for your response.

Best regards,
Kai

**Comment by julianu** [comment]
Hej Kai,

There are only two options, the named "best" and "all". I would recommend "best", as otherwise you will have a heavy bias on proteins, which were found by many spectra, but maybe only few peptides. If that is, what you need, you can use "all".

For "recommended parameters", there are some, which are basically the ones set in the KNIME nodes (and also the slightly outdated web application). Also in the tutorial (https://github.com/mpc-bioinformatics/pia#tutorial) the most relevant parameters are explained.
But I can imagine it is not that easy to understand them right away, so feel free to ask here, if anything is unclear.

Best regards,
Julian

**Comment by cksakura** [comment]
Hello Julian,

Thanks a lot!

Best regards,
Kai
