### ISSUE TITLE
problem trying to apply a PSM filter on X!Tandem Expect value

### ISSUE THREAD

**Issue by olangella** [mpc-bioinformatics/pia#41]
Sorry, it' me again ;-)

I've some difficulties to use the PIA Analysis module and I have some questions about how to use it.

I've set a filter at the PSM level.
I've chosen "X!Tandem expect < 0.01"
saved the resulting tables in XLS sheet adapter (after a column rename).
Then I did the same with : 
 "X!Tandem expect < 0.05"
I have the same protein list and same peptide list after an "occam's razor".
That's strange for me : I was expecting a different protein/group list.
the PSM results are different, as I was expecting, there are less PSM's in the list with the 0.01 filter than with 0.05.
So the filter is taken into account...
I've you an idea of what I'm missing ?

Cheers,
Olivier

**Comment by julianu** [comment]
It is probably a bit confusing in the beginning:
The filters only apply for the level, where you set them. Meaning: if you apply the PSM filter on the PSM tab in the settings dialog, they are filtered only for the PSM output. If you set them on the peptides level, only the filtered PSMs are used for peptide inference and reported in the respective port. So the ports for PSMs and peptides are NOT (necessarily) the ones used for protein inference, but according to the set filters at the respective level (and, at the moment, for only one given input file, if you should have multiple).

If you want to filter the PSMs for Protein inference, you have to set the inference filters accordingly on the protein tab. And don't forget to click "Add" after adjusting the settings ;)
Most probably you also want to set the base-score for inference to the same just filtered score, in your case X!Tandem expect. And, if you are not performing an FDR estimation, it is faster to turn off all options saying something about it.

I probably should highlight this more in the wiki texts, I guess you had a look [here](https://github.com/mpc-bioinformatics/pia/wiki/Running-PIA-via-KNIME#performing-a-pia-analysis) already.

Cheers, let me know, if this helped you. Otherwise, don't hesitate to ask!

**Comment by olangella** [comment]
Yes I had a look at the wiki before but I didn't get that.

Ok, I better understand now. I've checked the base-score too on X!Tandem expect.

So, this is where also I suppose I can filter to remove from inference the contaminant protein accessions, and also perhaps filter the reversed sequences (decoy) ?

Thanks for your help
Olivier

**Comment by julianu** [comment]
Right, here you can filter for them as well, using regular expressions. A real decoy-filter is under development.
Keep in mind, that when using more than one filter only the "&&" operator is used, which means that only the PSMs which fulfill all filters are passed to the protein inference.

Actually, filtering the decoys here is ok, if you don't want to calculate a protein level FDR (Which I would recommend, though - http://www.ncbi.nlm.nih.gov/pubmed/27498275).

For the contaminants: I would recommend to filter these after the inference, in the protein level filters. For this actually you could use a default KNIME "Row filter" as well. But that might be a question of taste as well ;)

Yeah, writing a tutorial/documentation is always hard. But it's good to know, where the problems are. So, you help me with asking questions.

**Comment by julianu** [comment]
Hej Olivier,
Did the filtering work out? I will shortly put a more elaborate tutorial online as well, which might help you in the future.

**Comment by olangella** [comment]
HI Julian,
Your advises were a great help for me. And indeed I've managed to filter my data as desired, but I forgot to make a feed back :(

Thanks again
Olivier
