### ISSUE TITLE
mztab issues for the PRIDE XML example

### ISSUE THREAD

**Issue by ypriverol** [mpc-bioinformatics/pia#9]
@julianu:
 Some comments about the mztab example:
- [x]  In the metadata modifications are annotated like:

> MTD   fixed_mod[1]    [MS, MS:1002453, No fixed modifications searched, ]
> MTD   variable_mod[1] [MS, MS:1002454, No variable modifications searched, ]

 However, the PSMs contains modifications
- [x] The theoretical mass is not present for any PSM. 
- [ ] We add in the document some comments saying that this is annotated like a merge.
- [x] We need to check the how do you define uniqueness at psm level. 
- [x] Can be possible to generate statistics at peptide level. For example if we said 1% at Peptide 
       Level is that possible. 
- [x] Some of the redundant annotations should be removed for example:

> MTD   software[9]-setting[10] base score for FDR calculation for file 8 = mascot_score
- [x] In the PSM Section the only Mascot is expressed in the search_engine column as search engine. However PIA in providing a search engine score but is not annotated like that:

> search_engine search_engine_score[1]  search_engine_score[2]

**Comment by julianu** [comment]
Thanks for the comments, most of them should be resolvable.

Comments to two of the points:
* Regarding the PSM uniqueness: a PSM is marked as unique, if it was assigned to only one accession in the imported dataset. For search engine results, this should be unproblematic, but with PRIDE XML, it could be already filtered (there is simply not all protein-PSM information in the file) and therefore must be annotated with a database, to be correct. Here the question would be, which database to use...
* PIA and peptide level can be done, but actually not with the spectrum extractor (because it does not work with peptides). If we switch to Occam's Razor for protein inference, we could filter for 1% FDR on peptide level. The sole calculation of peptide FDR though would be possible with both approaches (if you need only this)

**Comment by ypriverol** [comment]
@julianu:
  Regarding the uniqueness we could base our assumption in the filtered data, then it can be 
  computed. Then for a PSM to be annotated as non-unique should be associated with more than one 
  Protein id.  
  Our approach and what we aim to merge all the results into one big peptide file with 1% peptide FDR 
  considering peptide as sequence+modifications. For now we can work with 1% FDR at psm level but if 
  we can filter for 1% peptide level would be great for our use case.  Related with this, would be great to 
  have for our example PRIDE XML project the number of peptides for single merge, 1% psm FDR and 
  1% peptide FDR. Another thing, if we generate the peptide level statistics can we generate a PIA FDR 
  score for it?

**Comment by julianu** [comment]
@ypriverol Ok, so we can check the PSM uniqueness button above ;)

Conceptual, when using the SpectrumExtractor for inference, peptides are not directly referenced, but always PSMs. If we switch to OccamsRazor, a peptide FDR filter (or any other) would be possible. I guess, for PRIDE XML import, there are not many spectra with more than one peptide associated (are there any at all?). If so, using SpectrumExtractor would have few benefits, anyways.

**Comment by ypriverol** [comment]
@Julian I guess we can evaluate which of both approaches are better. Things to take into account:
 1 - quality of the results. We are exporting the peptide evidences. Then, an estimation of the FDR at peptide level would be better.
 2 - statistical assessment between both methods.
 3 - performance in terns of time, memory, etc

**Comment by julianu** [comment]
mzTab import and export should work by now.
Please re-open a new issue, if something does not work yet.
